name: Brat CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: brat/

    steps:
    # from: https://raehik.github.io/2021/03/01/caching-stack-and-cabal-haskell-builds-on-github-actions.html
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.6.4'
        cabal-version: '3.4'
        enable-stack: true

    - uses: actions/cache@v4
      with:
        path: |
          ~/.stack
          .stack-work
          */.stack-work
          ~/.cargo
          ${{ steps.setup.outputs.ghc-path }}
          ${{ steps.setup.outputs.cabal-path }}
          ${{ steps.setup.outputs.stack-path }}
        # best effort for cache: tie it to Stack resolver and package config
        key: ${{ runner.os }}-stack-${{ hashFiles('brat/stack.yaml',
                                                  'hugr_validator/Cargo.toml',
                                                  'hugr_extension/Cargo.toml'
                                                  ${{ steps.setup.outputs.ghc-version }}) }}
        restore-keys: |
          ${{ runner.os }}-stack
        save-always: true

    - name: Install dependencies
      run: stack build --only-dependencies
    - name: Build
      run: stack build --ghc-options "-O0"
    - name: Build stack tests
      run: stack test --no-run-tests --no-run-benchmarks --ghc-options "-O0"
    - name: Run stack tests
      run: stack test --ta --hide-successes

    # Validate the hugr outputs
    - name: Check for hugr_validator
      id: cached_validator
      run: |
        if [ -f ~/.cargo/bin/hugr_validator ]; then
            echo "out=true" >> $GITHUB_OUTPUT
        else
            echo "We need to build hugr_validator"
            echo "out=false" >> $GITHUB_OUTPUT
        fi

    - name: Install rust
      if: ${{ steps.cached_validator.outputs.out != 'true' }}
      uses: dtolnay/rust-toolchain@stable
    - name: Install hugr_validator
      if: ${{ steps.cached_validator.outputs.out != 'true' }}
      run: cargo install --path ../hugr_validator
    - name: Validate compilation output
      run: tools/validate.sh
