name: Brat CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.6'
        cabal-version: '3.4'
        enable-stack: true

    # from: https://raehik.github.io/2021/03/01/caching-stack-and-cabal-haskell-builds-on-github-actions.html
    - uses: actions/cache@v2
      with:
        path: |
          ~/.stack
          .stack-work
        # best effort for cache: tie it to Stack resolver and package config
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack

    - name: Install dependencies
      run: stack build --only-dependencies
    - name: Build
      run: stack build --ghc-options "-O0"
    - name: Build stack tests
      run: stack test --no-run-tests --no-run-benchmarks --ghc-options "-O0"
    - name: Run stack tests
      run: stack test --ta --hide-successes
